Emma = input("When is your birthday, Emma? ")
Liam = input("When is your birthday, Liam? ")
Sophia = input("When is your birthday, Sophia? ")
Noah = input("When is your birthday, Noah? ")
Ava = input("When is your birthday, Ava ? ")
print("Emma's birthday is "+Emma)
print("Liam's birthday is "+Liam)
print("Sophia's birthday is "+Sophia)
print("Noah's birthday is "+Noah)
print("Ava's birthday is "+Ava)